import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import { homedir } from "os";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
If you want to view the source, please visit the github repository of this plugin
Generated ${new Date().toDateString()} at ${new Date().toTimeString()}
*/
`;

const prod = process.argv[2] === "production";

esbuild
	.build({
		banner: {
			js: banner,
		},
		entryPoints: ["src/main.ts", "src/styles.css"],
		bundle: true,
		external: [
			"obsidian",
			"electron",
			"@codemirror/autocomplete",
			"@codemirror/collab",
			"@codemirror/commands",
			"@codemirror/language",
			"@codemirror/lint",
			"@codemirror/search",
			"@codemirror/state",
			"@codemirror/view",
			"@lezer/common",
			"@lezer/highlight",
			"@lezer/lr",
			...builtins,
		],
		loader: { ".png": "dataurl" },
		format: "cjs",
		watch: !prod,
		logLevel: "info",
		minify: prod,
		sourcemap: prod ? false : "inline",
		treeShaking: true,
		outdir: `${homedir()}/Library/Mobile Documents/iCloud~md~obsidian/Documents/Notes/.obsidian/plugins/obsidian-insert-things-link/`,
	})
	.catch(() => process.exit(1));
